spring:
    datasource:
        url: jdbc:h2:mem:appDb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS appDb
        username: sa
        password: password
        driverClassName: org.h2.Driver
        name: appDb

    jpa:
        defer-datasource-initialization: true
        hibernate:
            update
        hbm2ddl:
            auto: create
app:
    name: BookShop application
    api:
      title: BookShop  APIs
      version: 1.0.0
      description: BookShop  APIs description
      base-package: com.bookshop
      swagger:
        enable: true


