name: Daily Build and Analyze

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight

jobs:
  build_and_analyze:
    name: Build and Analyze Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Web UI tests
        run: mvn failsafe:integration-test
      - name: Generate coverage report
        run: mvn jacoco:report
        working-directory: Bookshop/
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./Booskshop/jacoco-report/jacoco.xml
